replication_factor = 1
consistency_mode = "consistent"

metadata_dir = "/var/garage/meta"
data_dir = "/var/garage/data"
metadata_snapshots_dir = "/var/garage/snapshots"

metadata_fsync = true #
data_fsync = true #
disable_scrub = true  #
use_local_tz = true	# 
metadata_auto_snapshot_interval = "6h"

db_engine = "lmdb"
lmdb_map_size = "1T"

block_size = "10M" #default 1M
block_ram_buffer_max = "256MiB"
block_max_concurrent_reads = 16

compression_level = 1

allow_punycode = false

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "fbbf2ff0ee8ca49d715b783e420d0cfd45d5d54cd9dce49375d5e2c0edacd4f3"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.localhost"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "uR7XRfLv+DGfTr713veWMRRMHFxn/2LwT6bvs54ye38="
metrics_token = "Ft2GExCiL5cx864TYlYO4UK+0hZc/NVYpiX+z4MhGnM="
